### ISSUE TITLE
Contribution Section

### ISSUE THREAD

**Issue by Quantum158** [epstechtheatre/epstechtheatre.github.io#24]
Need pages with the following content

- [ ] Basic contributing info with all information on basic text editing
- [ ] More advanced page editing including html elements such as notes and images
- [ ] Text editors
- [ ] Pull requests
- [ ] ...

**Comment by Quantum158** [comment]
Contributing has been moved to a separate workflow, this is not required now

**Comment by EPSWebPreview** [comment]
Commands can only be used in pull requests (which this thread is not)

**Comment by Quantum158** [comment]
test

**Comment by EPSWebPreview** [comment]
Commands can only be used in pull requests (which this thread is not)

**Comment by Quantum158** [comment]
test

**Comment by Quantum158** [comment]
test

**Comment by Quantum158** [comment]
test

**Comment by Quantum158** [comment]
@EPSWebPreview

**Comment by EPSWebPreview** [comment]
Commands can only be used in pull requests (which this thread is not)
